Add Login/Registration page
Galelya97/loft-taxi pull request #1
Opened 2021-01-19 19:06 UTC by Galelya97

Создан компонент страницы “Логин”, “Регистрация”, “Карта”,  “Профиль”. 
В компоненте добавлены кнопки навигации: карта, профиль, выйти. 
Навигация сделана при помощи стейта. 
Сверстана форма логина и форма регистрации. 
При <submite> пользователь попадает на страницу с картой.

2021-01-19 19:37 UTC, R-Oscar requested changes

2021-01-19 19:37 UTC, R-Oscar commented on package.json
> +    "normalize.css": "^8.0.1",
В Material UI же есть `<CssBaseline />`, зачем ещё normalize?)

https://material-ui.com/ru/components/css-baseline/

2021-01-19 19:37 UTC, R-Oscar commented on src/components/App/App.js
> +    this.state = { currentPage: "home", isLogin: false, login: "" };
state лучше вынести из конструктора, как у тебя сделано в LoginForm

2021-01-19 19:37 UTC, R-Oscar commented on src/components/App/App.js
> +    this.state = { currentPage: "home", isLogin: false, login: "" };
И давай isLogin переименуем в isLoggedIn

2021-01-19 19:37 UTC, R-Oscar commented on src/components/App/App.js
> +            {this.state.login}
Не совсем понятно из названия что здесь должно быть. Реакт компонент? Строка? Функция?

2021-01-19 19:37 UTC, R-Oscar commented on src/components/App/App.js
> +            {this.state.login}
По коду понял, что тут имя пользователя, тогда лучше переименовать в `this.state.username`

2021-01-19 19:37 UTC, R-Oscar commented on src/components/registrationForm/index.jsx
> +  state = { login: "", password: "", name: "", isLoading: false };
Круто, что эмулирована загрузка 👍

2021-01-19 19:37 UTC, R-Oscar commented on src/components/App/App.js
> +        {this.state.isLogin ? (
Здесь и далее можно разворачивать переменные из стейта/пропсов перед return в рендере:

`const { isLogin } = this.state `

Это упрощает читаемость кода. Но если тебе удобнее с this.state.isLogin, можешь оставить так

2021-01-20 09:44 UTC, R-Oscar approved these changes

2021-02-02 09:43 UTC, Galelya97 commented
Подправлен визуал,
Добавлена карта mapbox на background всех вкладок,
Указаны типы пропсов для компонентов,
Созданы контексты авторизации,
Использован хук useContext, useEffect,useState,
Не получилось сделать react-testing-library.

2021-02-03 11:01 UTC, R-Oscar requested changes

2021-02-03 11:01 UTC, R-Oscar commented on src/components/App/App.js
> +import s from "./App.module.css";
Лучше таких однобуквенных названий избегать, назови как-нибудь `classes` хотя бы

2021-02-03 11:01 UTC, R-Oscar commented on src/components/header/index.jsx
> +import s from "./styles.module.css";
И тут тоже лучше переименовать

2021-02-03 11:01 UTC, R-Oscar commented on src/components/App/App.js
> +export default withAuth(App);
Тут тебе не нужен хок withAuth, ты ведь доступ к контексту через `useContext` получаешь

2021-02-03 11:01 UTC, R-Oscar commented on src/components/header/index.jsx
> +  onLogout: PropTypes.func,
У тебя же нет этих пропсов в компоненте, зачем для них propTypes?

2021-02-03 11:01 UTC, R-Oscar commented on src/components/loginForm/index.jsx
> +      loginError = "Пустой логин";
Тут будет проще сразу делать `return setLoginError("")`, тогда не нужна будет лишняя переменная и условие на 38 строке

2021-02-03 11:01 UTC, R-Oscar commented on src/components/loginPage/index.jsx
> +  onLogin: PropTypes.func,
Тоже не юзается в компоненте

2021-02-03 11:33 UTC, Galelya97 commented on src/components/loginForm/index.jsx
> +      loginError = "Пустой логин";
Исправила , но в форме для регистрации я бы хотела оставить такую реализацию .

2021-03-04 16:29 UTC, R-Oscar requested changes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/App/App.js
> +const App = ({ isLoggedIn }) => {
Не хватает PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/carSelect/index.js
> +const CarCard = ({ title, cost, selected, onClick, img }) => (
PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/carSelect/index.js
> +const CarSelect = ({ className }) => {
PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/carSelect/index.js
> +            key={index}
Давай лучше заюзаем `item.title` в качестве ключа. Индекс лучше не использовать

2021-03-04 16:29 UTC, R-Oscar commented on src/components/carSelect/index.js
> +        style={{ marginTop: 20 }}
Стиль лучше вынести в класс в CSS-модуль

2021-03-04 16:29 UTC, R-Oscar commented on src/components/customSelect/index.js
> +        3
Тут тройка должна быть?

2021-03-04 16:29 UTC, R-Oscar commented on src/components/customSelect/index.js
> +          <MenuItem key={index} value={item.value}>
Тоже лучше key поменять на какое-нибудь уникальное значение в item, наверняка такое есть

2021-03-04 16:29 UTC, R-Oscar commented on src/components/errorRouteForm/index.jsx
> +          Перейти в форму
Тут лучше воспользоваться [Link](https://reactrouter.com/web/api/Link) из react-router

2021-03-04 16:29 UTC, R-Oscar commented on src/components/errorRouteForm/index.jsx
> +          style={{ marginTop: 14 }}
Тоже лучше вынести стилизацию в класс, чтобы было в едином стиле

2021-03-04 16:29 UTC, R-Oscar commented on src/components/header/index.jsx
> +const Header = ({ logOut }) => {
PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/header/styles.module.css
> +/*button {*/
Такие комменты лучше выпиливать перед коммитом

2021-03-04 16:29 UTC, R-Oscar commented on src/components/header/styles.module.css
> +  color: white;
Лучше тоже явно прописать `#ffffff`, как и в остальных местах

2021-03-04 16:29 UTC, R-Oscar commented on src/components/loginForm/index.jsx
> +  toggleForm: PropTypes.func,
Надо добавить новые пропсы сюда

2021-03-04 16:29 UTC, R-Oscar commented on src/components/loginForm/index.jsx
> +  const [login, setLogin] = useState("");
Тут желательно форму переписать на formik

2021-03-04 16:29 UTC, R-Oscar commented on src/components/loginForm/index.jsx
> +          style={{ marginTop: 20 }}
Тоже надо вынести стиль в отдельный класс

2021-03-04 16:29 UTC, R-Oscar commented on src/components/loginForm/loginForm.spec.js
> +      submit.click();
Это же по сути уже другой тест-кейс, лучше вынести его в отдельный `it("should ...")` блок

2021-03-04 16:29 UTC, R-Oscar commented on src/components/loginPage/index.jsx
> +const LoginPage = ({ logIn, authLoading, registration }) => {
PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/main/index.jsx
> +const Main = ({ logOut, route }) => {
PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/map/index.jsx
> +    console.log("componentDidUpdate");
Лишняя консоль

2021-03-04 16:29 UTC, R-Oscar commented on src/components/map/index.jsx
> +      this.map.on("load", () => {
Вот этот блок с `.on("load")` лучше в `componentDidMount` перенести

2021-03-04 16:29 UTC, R-Oscar commented on src/components/map/index.jsx
> +      // <div className={style.mapWrapper}>
Тоже лишние комменты

2021-03-04 16:29 UTC, R-Oscar commented on src/components/profile/index.jsx
> +const Profile = ({
PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/profile/index.jsx
> +  useEffect(() => {
Этот эффект тут точно нужен? У тебя же `initialValues` уже подгружаются в формике. При каком сценарии данные карты могут обновиться (в пропсах)?

2021-03-04 16:29 UTC, R-Oscar commented on src/components/profile/index.jsx
> +                  {formik.values.date.trim() === "/"
Лучше это условие вынести в переменную, например `formattedDate`

2021-03-04 16:29 UTC, R-Oscar commented on src/components/profile/index.jsx
> +                {formik.values.number.trim()
И это тоже в `formattedCardNumber`

2021-03-04 16:29 UTC, R-Oscar commented on src/components/profile/styles.module.css
> +.titleWrapper .desc {
Пустые селекторы лучше убрать

2021-03-04 16:29 UTC, R-Oscar commented on src/components/registrationForm/index.jsx
> +  toggleForm: PropTypes.func,
Тоже надо добавить новые пропсы

2021-03-04 16:29 UTC, R-Oscar commented on src/components/registrationForm/index.jsx
> +  const [login, setLogin] = useState("");
Тут я бы тоже формик воткнул, это избавит от кучи `useState`, и валидация будет проще

2021-03-04 16:29 UTC, R-Oscar commented on src/components/registrationForm/index.jsx
> +          style={{ marginTop: 20 }}
Тоже в класс

2021-03-04 16:29 UTC, R-Oscar commented on src/components/routePage/index.jsx
> +      {/*{route.length ? (*/}
Надо убрать коммент

2021-03-04 16:29 UTC, R-Oscar commented on src/components/routePage/index.jsx
> +  addressList,
PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/components/routePage/index.jsx
> +      {cardInfo ? (
Тут идет сложное условие в рендере, таких нужно избегать.
Можно упростить так

```
if (!cardInfo) return <ErrorRouteForm />

if (!route.length) return <RouteSelect ... />

return <SuccessRouteForm .../>
```

2021-03-04 16:29 UTC, R-Oscar commented on src/components/routePage/index.jsx
> +            requestAddressList={requestAddressList}
Эти три пропса они же все с редакса идут, зачем их на этом уровне подключать? Пусть RouteSelect к ним и подрубается

2021-03-04 16:29 UTC, R-Oscar commented on src/components/routeSelect/index.jsx
> +  const optionsAddresses = addressList.map((item) => ({
Не совсем понятно зачем тут этот маппинг. `optionsAddresses` у тебя потом летит в `customSelect` и там маппится повторно, лучше один раз сделать мап

2021-03-04 16:29 UTC, R-Oscar commented on src/components/customSelect/index.js
> +    onChange({ target: { value: "" } });
Эта конструкция очень костыльно выглядит, попробуй на верхнем уровне прописать функцию которая будет очищать стейт и вызывать эту функцию отсюда

То есть на уровне routeSelect:

`const handleClearFrom = () => setFrom("")`
`<CustomSelect onClear={handleClearFrom} ... />`

Ну и в этом обработчике соответственно надо просто вызвать `onClear();`

2021-03-04 16:29 UTC, R-Oscar commented on src/components/App/App.module.css
> +.map {
Пустой селектор, лучше убрать

2021-03-04 16:29 UTC, R-Oscar commented on src/components/successPaymentForm/index.jsx
> +          Перейти на карту
Тоже лучше поменять на `<Link />` из `react-router`

2021-03-04 16:29 UTC, R-Oscar commented on src/components/successRouteForm/index.jsx
> +const SuccessRouteForm = ({ setRoute }) => {
PropTypes

2021-03-04 16:29 UTC, R-Oscar commented on src/saga/auth/sagas.js
> +  } catch (e) {}
Тут и везде в catch-блоках нужно в toast сообщение выводить, либо в консоль через `console.error()`
А лучше и так и так

2021-03-06 08:18 UTC, Galelya97 commented on src/components/routeSelect/index.jsx
> +  const optionsAddresses = addressList.map((item) => ({
это сделано для удобного переиспользования customSelect  в других компjнентах , он должен принимать не массив строк , а более удобный вариант в качестве объекта с полями value и label.

2021-03-06 09:54 UTC, Galelya97 commented on src/components/profile/index.jsx
> +  useEffect(() => {
если вдруг логика загрузки данных поменяется или запрос будет долго идти, пользователь может попасть на страницу где данные ещё не подгружены, а затем они придут и упадут в store, на этот случай этот useEffect

2021-03-06 10:13 UTC, Galelya97 commented on src/components/carSelect/index.js
> +        style={{ marginTop: 20 }}
не дает материал вынести в класс

2021-03-09 06:08 UTC, R-Oscar approved these changes

2021-03-09 06:08 UTC, R-Oscar commented on src/components/App/App.js
> +App.prototype = {
PropTypes

2021-03-19 16:04 UTC, merged